keepHatOnDeath = true
seasonalBagChance = 7
enableMobLoot = true
enableChestLoot = true
allowHatInHelmetSlot = false
chestNoneWeight = 50
chestCommonWeight = 7
chestUncommonWeight = 5
chestRareWeight = 3
chestEpicWeight = 2
entityNoneWeight = 67
entityCommonWeight = 7
entityUncommonWeight = 5
entityRareWeight = 3
entityEpicWeight = 2
